// ============================================================
// UNIVERSO MERCHAN — Configurator Engine
// ============================================================
// Core business logic for the product customization flow.
// Orchestrates: position → technique → parameters → price → mockup
//
// This module is FRAMEWORK-AGNOSTIC (pure TypeScript).
// The React components import and use these functions.
// ============================================================

import {
  calculatePrintPrice,
  isWhiteTextileVariant,
  type PrintPriceCalculation,
} from "./midocean-api";
import {
  calculateFullPrice,
  getScaledPrice,
  type MarginConfig,
  type ProductPriceScale,
  type PrintCostBreakdown,
  type PriceCalculationResult,
} from "./price-calculator";

// ============================================================
// TYPES — State of the configurator at any point
// ============================================================

export interface ConfiguratorState {
  // Step tracking
  currentStep: 1 | 2 | 3;  // 1=Product, 2=Customize, 3=Review
  
  // Product selection (Step 1)
  product: ConfigProduct;
  selectedVariantIndex: number;
  quantity: number;
  
  // Customization (Step 2) — null means "sin marcaje"
  customization: CustomizationConfig | null;
  
  // Computed pricing (updates in real-time)
  pricing: PriceCalculationResult;
  
  // Ready for cart?
  isComplete: boolean;
  validationErrors: string[];
}

export interface ConfigProduct {
  masterCode: string;
  name: string;
  shortDescription: string;
  material: string;
  isTextile: boolean;  // Affects white/non-white color rule for ST technique
  variants: ConfigVariant[];
  priceScales: ProductPriceScale[];
  printPositions: ConfigPrintPosition[];
}

export interface ConfigVariant {
  sku: string;
  variantId: string;
  color: string;
  colorCode: string;
  colorHex: string;
  size?: string;
  stock: number;
  images: {
    front?: string;
    back?: string;
    detail?: string;
    highRes?: string;
  };
}

export interface ConfigPrintPosition {
  positionId: string;
  name: string;
  maxWidthMm: number;
  maxHeightMm: number;
  positionImage?: string;  // Image showing print zone on product
  techniques: ConfigTechnique[];
}

export interface ConfigTechnique {
  techniqueId: string;
  name: string;
  description: string;
  pricingType: "NumberOfColours" | "NumberOfPositions" | "AreaRange" | "ColourAreaRange";
  maxColors?: number;
  // Pricing data (from print pricelist, pre-loaded)
  setup: number;
  setupRepeat: number;
  nextColourCostIndicator: boolean;
  varCosts: any[];  // Complex nested structure from Midocean
}

export interface CustomizationConfig {
  positions: CustomizationPosition[];
  artwork: ArtworkConfig | null;
}

export interface CustomizationPosition {
  positionId: string;
  positionName: string;
  techniqueId: string;
  techniqueName: string;
  pricingType: string;
  
  // Parameters (varies by pricing type)
  numColors: number;       // For NumberOfColours & ColourAreaRange
  numPositions: number;    // For NumberOfPositions (usually 1 per position)
  printWidthMm: number;    // User-defined (must be ≤ maxWidth)
  printHeightMm: number;   // User-defined (must be ≤ maxHeight)
  areaCm2: number;         // Computed: (width * height) / 100
  
  // PMS colors selected (for Midocean order)
  pmsColors: string[];
  
  // Print instruction text
  instructions: string;
}

export interface ArtworkConfig {
  fileName: string;
  fileSize: number;
  fileType: string;         // "application/pdf", "image/png", etc.
  fileUrl: string;          // Uploaded to our server
  uploadedAt: Date;
  
  // Mockup generated by our visualizer
  mockupUrl: string | null;
  mockupGeneratedAt: Date | null;
}

// ============================================================
// INITIAL STATE — Create a fresh configurator for a product
// ============================================================

export function createConfiguratorState(
  product: ConfigProduct,
  margins: MarginConfig,
  initialQuantity: number = 50,
): ConfiguratorState {
  const pricing = calculateFullPrice({
    quantity: initialQuantity,
    productPriceScales: product.priceScales,
    printCosts: null,
    margins,
  });
  
  return {
    currentStep: 1,
    product,
    selectedVariantIndex: 0,
    quantity: initialQuantity,
    customization: null,
    pricing,
    isComplete: false,
    validationErrors: [],
  };
}

// ============================================================
// ACTIONS — Each returns a new state (immutable updates)
// ============================================================

// Change variant (color/size)
export function selectVariant(
  state: ConfiguratorState,
  variantIndex: number,
  margins: MarginConfig,
): ConfiguratorState {
  const newState = { ...state, selectedVariantIndex: variantIndex };
  return recalculatePrice(newState, margins);
}

// Change quantity
export function setQuantity(
  state: ConfiguratorState,
  quantity: number,
  margins: MarginConfig,
): ConfiguratorState {
  const clampedQty = Math.max(1, Math.min(quantity, 99999));
  const newState = { ...state, quantity: clampedQty };
  return recalculatePrice(newState, margins);
}

// Go to step 2 (start customization)
export function startCustomization(state: ConfiguratorState): ConfiguratorState {
  return {
    ...state,
    currentStep: 2,
    customization: {
      positions: [],
      artwork: null,
    },
  };
}

// Skip customization (buy without printing)
export function skipCustomization(state: ConfiguratorState): ConfiguratorState {
  return {
    ...state,
    currentStep: 3,
    customization: null,
    isComplete: true,
    validationErrors: [],
  };
}

// Select a print position
export function selectPosition(
  state: ConfiguratorState,
  positionId: string,
): ConfiguratorState {
  if (!state.customization) return state;
  
  const position = state.product.printPositions.find(p => p.positionId === positionId);
  if (!position) return state;
  
  // Check if position already added
  const existing = state.customization.positions.find(p => p.positionId === positionId);
  if (existing) return state;
  
  return {
    ...state,
    customization: {
      ...state.customization,
      positions: [
        ...state.customization.positions,
        {
          positionId: position.positionId,
          positionName: position.name,
          techniqueId: "",         // Must be selected next
          techniqueName: "",
          pricingType: "",
          numColors: 1,
          numPositions: 1,
          printWidthMm: Math.round(position.maxWidthMm * 0.8),  // Default 80% of max
          printHeightMm: Math.round(position.maxHeightMm * 0.8),
          areaCm2: 0,
          pmsColors: [],
          instructions: "",
        },
      ],
    },
  };
}

// Remove a print position
export function removePosition(
  state: ConfiguratorState,
  positionId: string,
  margins: MarginConfig,
): ConfiguratorState {
  if (!state.customization) return state;
  
  const newState = {
    ...state,
    customization: {
      ...state.customization,
      positions: state.customization.positions.filter(p => p.positionId !== positionId),
    },
  };
  return recalculatePrice(newState, margins);
}

// Select technique for a position
export function selectTechnique(
  state: ConfiguratorState,
  positionId: string,
  techniqueId: string,
  margins: MarginConfig,
): ConfiguratorState {
  if (!state.customization) return state;
  
  const position = state.product.printPositions.find(p => p.positionId === positionId);
  const technique = position?.techniques.find(t => t.techniqueId === techniqueId);
  if (!technique) return state;
  
  const newPositions = state.customization.positions.map(p => {
    if (p.positionId !== positionId) return p;
    
    const width = p.printWidthMm;
    const height = p.printHeightMm;
    const areaCm2 = (width * height) / 100;
    
    return {
      ...p,
      techniqueId: technique.techniqueId,
      techniqueName: technique.name,
      pricingType: technique.pricingType,
      areaCm2,
      numColors: technique.pricingType === "NumberOfColours" || technique.pricingType === "ColourAreaRange" ? 1 : 0,
    };
  });
  
  const newState = {
    ...state,
    customization: { ...state.customization, positions: newPositions },
  };
  return recalculatePrice(newState, margins);
}

// Set number of colors for a position
export function setNumColors(
  state: ConfiguratorState,
  positionId: string,
  numColors: number,
  margins: MarginConfig,
): ConfiguratorState {
  if (!state.customization) return state;
  
  const newPositions = state.customization.positions.map(p => {
    if (p.positionId !== positionId) return p;
    const clamped = Math.max(1, Math.min(numColors, p.pricingType === "NumberOfColours" ? 8 : 12));
    return { ...p, numColors: clamped };
  });
  
  const newState = {
    ...state,
    customization: { ...state.customization, positions: newPositions },
  };
  return recalculatePrice(newState, margins);
}

// Set print dimensions for a position
export function setPrintDimensions(
  state: ConfiguratorState,
  positionId: string,
  widthMm: number,
  heightMm: number,
  margins: MarginConfig,
): ConfiguratorState {
  if (!state.customization) return state;
  
  const maxPos = state.product.printPositions.find(p => p.positionId === positionId);
  if (!maxPos) return state;
  
  const newPositions = state.customization.positions.map(p => {
    if (p.positionId !== positionId) return p;
    const w = Math.max(1, Math.min(widthMm, maxPos.maxWidthMm));
    const h = Math.max(1, Math.min(heightMm, maxPos.maxHeightMm));
    return { ...p, printWidthMm: w, printHeightMm: h, areaCm2: (w * h) / 100 };
  });
  
  const newState = {
    ...state,
    customization: { ...state.customization, positions: newPositions },
  };
  return recalculatePrice(newState, margins);
}

// Set PMS colors
export function setPmsColors(
  state: ConfiguratorState,
  positionId: string,
  colors: string[],
): ConfiguratorState {
  if (!state.customization) return state;
  
  const newPositions = state.customization.positions.map(p =>
    p.positionId === positionId ? { ...p, pmsColors: colors } : p
  );
  
  return {
    ...state,
    customization: { ...state.customization, positions: newPositions },
  };
}

// Upload artwork
export function setArtwork(
  state: ConfiguratorState,
  artwork: ArtworkConfig,
): ConfiguratorState {
  if (!state.customization) return state;
  return {
    ...state,
    customization: { ...state.customization, artwork },
  };
}

// Set mockup URL (after visualizer generates it)
export function setMockupUrl(
  state: ConfiguratorState,
  mockupUrl: string,
): ConfiguratorState {
  if (!state.customization?.artwork) return state;
  return {
    ...state,
    customization: {
      ...state.customization,
      artwork: {
        ...state.customization.artwork,
        mockupUrl,
        mockupGeneratedAt: new Date(),
      },
    },
  };
}

// Go to review step
export function goToReview(state: ConfiguratorState): ConfiguratorState {
  const errors = validateState(state);
  return {
    ...state,
    currentStep: 3,
    isComplete: errors.length === 0,
    validationErrors: errors,
  };
}

// Go back to a step
export function goToStep(state: ConfiguratorState, step: 1 | 2 | 3): ConfiguratorState {
  return { ...state, currentStep: step };
}

// ============================================================
// PRICE RECALCULATION — Called after every change
// ============================================================

function recalculatePrice(
  state: ConfiguratorState,
  margins: MarginConfig,
): ConfiguratorState {
  let printCosts: PrintCostBreakdown | null = null;
  
  if (state.customization && state.customization.positions.length > 0) {
    let totalSetup = 0;
    let totalPrinting = 0;
    let totalHandling = 0;
    
    const variant = state.product.variants[state.selectedVariantIndex];
    const isNonWhiteTextile = state.product.isTextile && !isWhiteTextileVariant(variant?.colorCode || "");
    
    for (const pos of state.customization.positions) {
      if (!pos.techniqueId) continue;
      
      // Find the technique data with pricing
      const positionDef = state.product.printPositions.find(p => p.positionId === pos.positionId);
      const techniqueDef = positionDef?.techniques.find(t => t.techniqueId === pos.techniqueId);
      
      if (techniqueDef) {
        const calculation = calculatePrintPrice({
          technique: {
            id: techniqueDef.techniqueId,
            description: techniqueDef.name,
            pricing_type: techniqueDef.pricingType,
            setup: String(techniqueDef.setup),
            setup_repeat: String(techniqueDef.setupRepeat),
            next_colour_cost_indicator: String(techniqueDef.nextColourCostIndicator),
            var_costs: techniqueDef.varCosts,
          },
          quantity: state.quantity,
          numColors: pos.numColors,
          numPositions: pos.numPositions,
          areaCm2: pos.areaCm2,
          isRepeatOrder: false,
          isTextileNonWhite: isNonWhiteTextile,
          handlingPricePerUnit: 0.18,  // Default handling, overridden by actual data
        });
        
        totalSetup += calculation.setupCost;
        totalPrinting += calculation.printingCost;
        totalHandling += calculation.handlingCost;
      }
    }
    
    printCosts = {
      setupCost: totalSetup,
      printingCost: totalPrinting,
      handlingCost: totalHandling,
      totalCost: totalSetup + totalPrinting + totalHandling,
    };
  }
  
  const pricing = calculateFullPrice({
    quantity: state.quantity,
    productPriceScales: state.product.priceScales,
    printCosts,
    margins,
  });
  
  return { ...state, pricing };
}

// ============================================================
// VALIDATION — Check if the configuration is complete
// ============================================================

function validateState(state: ConfiguratorState): string[] {
  const errors: string[] = [];
  
  // Basic checks
  if (state.quantity < 1) {
    errors.push("La cantidad debe ser al menos 1 unidad");
  }
  
  const variant = state.product.variants[state.selectedVariantIndex];
  if (variant && state.quantity > variant.stock) {
    errors.push(`Stock insuficiente. Disponible: ${variant.stock} unidades`);
  }
  
  // Customization checks
  if (state.customization) {
    if (state.customization.positions.length === 0) {
      errors.push("Selecciona al menos una posición de impresión");
    }
    
    for (const pos of state.customization.positions) {
      if (!pos.techniqueId) {
        errors.push(`Selecciona técnica de impresión para la posición "${pos.positionName}"`);
      }
      
      if (pos.printWidthMm <= 0 || pos.printHeightMm <= 0) {
        errors.push(`Define el tamaño de impresión para "${pos.positionName}"`);
      }
      
      // Check max dimensions
      const maxPos = state.product.printPositions.find(p => p.positionId === pos.positionId);
      if (maxPos) {
        if (pos.printWidthMm > maxPos.maxWidthMm) {
          errors.push(`Ancho de impresión en "${pos.positionName}" excede el máximo (${maxPos.maxWidthMm}mm)`);
        }
        if (pos.printHeightMm > maxPos.maxHeightMm) {
          errors.push(`Alto de impresión en "${pos.positionName}" excede el máximo (${maxPos.maxHeightMm}mm)`);
        }
      }
      
      // Check colors for NumberOfColours type
      if (pos.pricingType === "NumberOfColours" || pos.pricingType === "ColourAreaRange") {
        if (pos.numColors < 1) {
          errors.push(`Selecciona al menos 1 color para "${pos.positionName}"`);
        }
      }
    }
    
    // Artwork check
    if (!state.customization.artwork) {
      errors.push("Sube tu logo o diseño para la personalización");
    }
  }
  
  return errors;
}

// ============================================================
// CART ITEM — Convert configurator state to a cart-ready item
// ============================================================

export interface CartItem {
  productMasterCode: string;
  productName: string;
  variantSku: string;
  variantId: string;
  color: string;
  colorCode: string;
  size?: string;
  quantity: number;
  
  // Pricing
  unitPriceProduct: number;
  unitPriceTotal: number;
  totalPrice: number;
  
  // Customization details (null if plain order)
  customization: {
    positions: Array<{
      positionId: string;
      positionName: string;
      techniqueId: string;
      techniqueName: string;
      printWidthMm: number;
      printHeightMm: number;
      numColors: number;
      pmsColors: string[];
      instructions: string;
    }>;
    artworkUrl: string;
    artworkFileName: string;
    mockupUrl: string | null;
  } | null;
  
  // For the order API
  orderType: "NORMAL" | "PRINT";
  
  // Image for display
  productImage: string;
}

export function stateToCartItem(state: ConfiguratorState): CartItem {
  const variant = state.product.variants[state.selectedVariantIndex];
  const hasCustomization = state.customization && state.customization.positions.length > 0;
  
  return {
    productMasterCode: state.product.masterCode,
    productName: state.product.name,
    variantSku: variant.sku,
    variantId: variant.variantId,
    color: variant.color,
    colorCode: variant.colorCode,
    size: variant.size,
    quantity: state.quantity,
    unitPriceProduct: state.pricing.productSellPerUnit,
    unitPriceTotal: state.pricing.pricePerUnit,
    totalPrice: state.pricing.totalPrice,
    customization: hasCustomization ? {
      positions: state.customization!.positions.map(p => ({
        positionId: p.positionId,
        positionName: p.positionName,
        techniqueId: p.techniqueId,
        techniqueName: p.techniqueName,
        printWidthMm: p.printWidthMm,
        printHeightMm: p.printHeightMm,
        numColors: p.numColors,
        pmsColors: p.pmsColors,
        instructions: p.instructions,
      })),
      artworkUrl: state.customization!.artwork?.fileUrl || "",
      artworkFileName: state.customization!.artwork?.fileName || "",
      mockupUrl: state.customization!.artwork?.mockupUrl || null,
    } : null,
    orderType: hasCustomization ? "PRINT" : "NORMAL",
    productImage: variant.images.front || "",
  };
}

// ============================================================
// MIDOCEAN ORDER — Convert cart item to Midocean Order Entry format
// ============================================================

export function cartItemToMidoceanOrderLine(
  item: CartItem,
  lineId: number,
): any {
  if (item.orderType === "NORMAL") {
    return {
      order_line_id: String(lineId * 10),
      sku: item.variantSku,
      variant_id: item.variantId,
      quantity: String(item.quantity),
      expected_price: "0",
    };
  }
  
  // PRINT order
  return {
    order_line_id: String(lineId * 10),
    master_code: item.productMasterCode,
    quantity: String(item.quantity),
    expected_price: "0",
    printing_positions: item.customization!.positions.map(pos => ({
      id: pos.positionId,
      print_size_height: String(pos.printHeightMm),
      print_size_width: String(pos.printWidthMm),
      printing_technique_id: pos.techniqueId,
      number_of_print_colors: String(pos.numColors),
      print_artwork_url: item.customization!.artworkUrl,
      print_mockup_url: item.customization!.mockupUrl || "",
      print_instruction: pos.instructions || "None",
      print_colors: pos.pmsColors.map(c => ({ color: c })),
    })),
    print_items: [{
      item_color_number: item.colorCode,
      ...(item.size ? { item_size: item.size } : {}),
      quantity: String(item.quantity),
    }],
  };
}

// ============================================================
// QUOTE / PRESUPUESTO — Generate data for PDF
// ============================================================

export interface QuoteData {
  quoteNumber: string;
  date: string;
  validUntil: string;
  clientName: string;
  clientEmail: string;
  clientCompany?: string;
  items: Array<{
    name: string;
    color: string;
    quantity: number;
    unitPrice: number;
    customization?: string;
    lineTotal: number;
  }>;
  subtotal: number;
  discount: number;
  discountPct: number;
  total: number;
  buyUrl: string;  // Direct link to restore cart and buy
}

export function stateToQuoteItem(state: ConfiguratorState): QuoteData["items"][0] {
  const variant = state.product.variants[state.selectedVariantIndex];
  const customDesc = state.customization?.positions.map(p =>
    `${p.positionName}: ${p.techniqueName}${p.numColors > 0 ? ` (${p.numColors} col.)` : ""}`
  ).join(" + ");
  
  return {
    name: state.product.name,
    color: variant.color + (variant.size ? ` / ${variant.size}` : ""),
    quantity: state.quantity,
    unitPrice: state.pricing.pricePerUnit,
    customization: customDesc || undefined,
    lineTotal: state.pricing.totalPrice,
  };
}
